name: "CD pipeline/workflow"
on:
  workflow_run:
    workflows:
      - "Sample ci pipeline/workflow"
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "setup node js"
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: "setup vercel cli"
        run: npm install -g vercel
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      
      - name: "Deploy to vercel"
        run: vercel --prod --token=${{ secrets.VERSEL_SECRET }} --confirm --name=ci-cd-react --cwd=./dist