name: "CD pipeline/workflow"
on:
  workflow_run:
    workflows: ["Sample React CI Pipeline / Workflow"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "setup node js"
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: "setup vercel cli"
        run: npm install -g vercel
      
      - name: "download build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      
      - name: "Deploy to vercel"
        run: vercel --prod --token=${{ secrets.VERSEL_SECRET }} --confirm --name=