name: "CD pipeline/workflow"

on:
  workflow_run:
    workflows:
      - "Sample ci pipeline/workflow"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: 

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Verify downloaded files
        run: |
          echo "Current directory:"
          pwd
          echo "Downloaded files:"
          ls -R dist

      - name: Deploy to Vercel
        run: |
          vercel deploy \
            --prod \
            --yes \
            --token=${{ secrets.VERSEL_SECRET }} \
            --name react-ci-cd-setup
      
      - name: Send failure email
        if: failure()
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PSWD: ${{ secrets.EMAIL_PSWD }}
          HR_EMAIL: ${{ secrets.HR_EMAIL }}
          WORKFLOW_NAME: CI Pipeline
        run: python3 script/send_email.py